-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 11:57:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imobiliaria
-- -----------------------------------------------------
-- Banco para registro de aluguel de imoveis

-- -----------------------------------------------------
-- Schema imobiliaria
--
-- Banco para registro de aluguel de imoveis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imobiliaria` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `imobiliaria` ;

-- -----------------------------------------------------
-- Table `imobiliaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `logradouro` VARCHAR(80) NULL,
  `numero` VARCHAR(6) NULL,
  `complemento` VARCHAR(30) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `telefone_residencial` VARCHAR(11) NULL,
  `telefone_celular` VARCHAR(11) NULL,
  `email` VARCHAR(180) NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `idx_nome` (`nome` ASC) INVISIBLE,
  INDEX `idx_documento` (`cpf_cnpj` ASC) INVISIBLE,
  INDEX `idx_cep` (`cep` ASC) INVISIBLE,
  INDEX `idx_telefone` (`telefone_residencial` ASC) INVISIBLE,
  INDEX `idx_celular` (`telefone_celular` ASC) INVISIBLE,
  INDEX `idx_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`tipo_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`tipo_imovel` (
  `id_tipo_imovel` INT NOT NULL,
  `tipo_imovel` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_imovel`),
  INDEX `idx_tipo_imovel` (`tipo_imovel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel` (
  `id_imovel` INT NOT NULL,
  `id_locador` INT NOT NULL COMMENT 'Identificador (tabela cliente) do proprietário do imóvel',
  `id_tipo_imovel` INT NOT NULL COMMENT 'Identifica se o imóvel é um apartamento, casa, casa geminada...',
  `titulo_anuncio` VARCHAR(60) NOT NULL COMMENT 'É o título do anúncio do imóvel para a apresentação em midias de anúncio de imóveis para alugar.',
  `descricao_imovel` VARCHAR(300) NOT NULL COMMENT 'Descrição detalhada do imóvel',
  `cep` CHAR(8) NOT NULL COMMENT 'CEP do endereço onde o imóvel se encontra',
  `logradouro` VARCHAR(80) NOT NULL COMMENT 'Nome da rua/avenida/rodovia em que o imóvel se encontra',
  `numero` VARCHAR(6) NOT NULL,
  `complemento` VARCHAR(30) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `area_aproximada` VARCHAR(10) NULL,
  `quartos` DECIMAL(2,0) NULL COMMENT 'Informa a quantidade de quartos que o imóvel possui',
  `banheiros` DECIMAL(2,0) NULL COMMENT 'Informa a quantidade de banheiros que o imóvel possui',
  `suite` DECIMAL(2,0) NULL COMMENT 'Informa quantas suítes o imóvel possui',
  `vaga_coberta` DECIMAL(2,0) NULL COMMENT 'Informa quantas vagas cobertas possui o imóvel',
  `vaga_descoberta` DECIMAL(2,0) NULL COMMENT 'Informa quantas vagas descobertas possui o imóvel',
  `elevador` TINYINT NULL COMMENT 'Informa se há elevador no imóvel',
  `valor_aluguel_proprietario` FLOAT NULL COMMENT 'Valor do aluguel que o proprietário propôs',
  `taxa_imobiliaria` DECIMAL(3,2) NULL COMMENT 'Taxa de manutenção da imobiliária sobre o valor do imóvel',
  `valor_condominio` FLOAT NULL COMMENT 'Valor médio do condomínio',
  `valor_iptu` FLOAT NULL COMMENT 'Valor médio do IPTU',
  PRIMARY KEY (`id_imovel`),
  INDEX `fk_locador_idx` (`id_locador` ASC) VISIBLE,
  INDEX `fk_id_tipo_imovel_idx` (`id_tipo_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_locador`
    FOREIGN KEY (`id_locador`)
    REFERENCES `imobiliaria`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_tipo_imovel`
    FOREIGN KEY (`id_tipo_imovel`)
    REFERENCES `imobiliaria`.`tipo_imovel` (`id_tipo_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imagem.imovel`
-- -----------------------------------------------------
CREATE TABLE `imagem_imovel` (
  `id_imagem` int NOT NULL,
  `id_imovel` int NOT NULL,
  `ordem_imagem` int DEFAULT NULL,
  `imagem` varchar(255) COLLATE utf8mb3_bin NOT NULL,
  PRIMARY KEY (`id_imagem`),
  KEY `fk_id_imovel_idx` (`id_imovel`),
  CONSTRAINT `fk_id_imovel` FOREIGN KEY (`id_imovel`) REFERENCES `imovel` (`id_imovel`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;


-- -----------------------------------------------------
-- Table `imobiliaria`.`locacao_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`locacao_imovel` (
  `id_locacao` INT NOT NULL,
  `id_imovel` INT NOT NULL COMMENT 'Identificador do imóvel para aluguel',
  `id_locatario` INT NOT NULL COMMENT 'Identificador do locatário (quem está alugando) do imóvel',
  `data_locacao` DATETIME NOT NULL COMMENT 'Data proposição do contrato de aluguel',
  `periodo_minino_locacao` DECIMAL(3,0) NOT NULL COMMENT 'Informa o período mínino, em dias, que o contrato deverá vigorar',
  `data_inicio_vigencia` DATE NOT NULL COMMENT 'Data início da vigência',
  `data_fim_vigencia` DATE NULL COMMENT 'Data fim da vigência conforme o período mínimo e/ou a data efetiva do distrato.',
  `valor_aluguel` FLOAT NOT NULL,
  `taxa_administracao` DECIMAL(3,2) NOT NULL COMMENT 'Taxa de administração sobre o valor do aluguel pertencente à administradora',
  `finalidade_locacao` VARCHAR(30) NOT NULL COMMENT 'Qual a finalidade da locação: moradia, empreendimento, sublocação (se permitido)',
  PRIMARY KEY (`id_locacao`),
  INDEX `idx_data_locacao` (`data_locacao` ASC) INVISIBLE,
  INDEX `idx_data_inicio_vig` (`data_inicio_vigencia` ASC) INVISIBLE,
  INDEX `idx_data_fim_vig` (`data_fim_vigencia` ASC) INVISIBLE,
  INDEX `idx_finalidade_loc` (`finalidade_locacao` ASC) VISIBLE,
  INDEX `fk_imovel_idx` (`id_imovel` ASC) VISIBLE,
  INDEX `fk_locatario_idx` (`id_locatario` ASC) VISIBLE,
  CONSTRAINT `fk_imovel`
    FOREIGN KEY (`id_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`id_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locatario`
    FOREIGN KEY (`id_locatario`)
    REFERENCES `imobiliaria`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
